fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    nsswitch:
      repo: 'https://github.com/ghoneycutt/puppet-module-nsswitch.git'
      ref: 'v1.5.0'
  symlinks:
    pam: "#{source_dir}"
